basePath: /api/v1
definitions:
  types.AWSAuth:
    properties:
      access_key_id:
        type: string
      secret_access_key:
        type: string
      session_token:
        type: string
    type: object
  types.AWSDomainValidateResponse:
    properties:
      validated:
        type: boolean
    type: object
  types.AWSProfilesResponse:
    properties:
      profiles:
        items:
          type: string
        type: array
    type: object
  types.CivoAuth:
    properties:
      token:
        type: string
    type: object
  types.CivoDomainValidationRequest:
    properties:
      cloud_region:
        type: string
    type: object
  types.CivoDomainValidationResponse:
    properties:
      validated:
        type: boolean
    type: object
  types.Cluster:
    properties:
      _id:
        type: string
      alerts_email:
        type: string
      argocd_auth_token:
        type: string
      argocd_create_registry_check:
        type: boolean
      argocd_delete_registry_check:
        type: boolean
      argocd_initialize_check:
        type: boolean
      argocd_install_check:
        type: boolean
      argocd_password:
        type: string
      argocd_username:
        type: string
      atlantis_webhook_secret:
        type: string
      atlantis_webhook_url:
        type: string
      aws_account_id:
        description: kms
        type: string
      aws_auth:
        allOf:
        - $ref: '#/definitions/types.AWSAuth'
        description: Auth
      aws_kms_key_detokenized_check:
        type: boolean
      aws_kms_key_id:
        type: string
      civo_auth:
        $ref: '#/definitions/types.CivoAuth'
      cloud_provider:
        type: string
      cloud_region:
        type: string
      cloud_terraform_apply_check:
        type: boolean
      cloud_terraform_apply_failed_check:
        type: boolean
      cluster_id:
        type: string
      cluster_name:
        type: string
      cluster_secrets_created_check:
        type: boolean
      cluster_type:
        type: string
      creation_timestamp:
        type: string
      do_auth:
        $ref: '#/definitions/types.DigitaloceanAuth'
      domain_liveness_check:
        type: boolean
      domain_name:
        type: string
      git_host:
        type: string
      git_init_check:
        type: boolean
      git_owner:
        type: string
      git_provider:
        type: string
      git_terraform_apply_check:
        type: boolean
      git_token:
        type: string
      git_user:
        type: string
      gitlab_owner_group_id:
        type: integer
      gitops_pushed_check:
        type: boolean
      gitops_ready_check:
        type: boolean
      in_progress:
        type: boolean
      install_tools_check:
        description: Checks
        type: boolean
      kbot_setup_check:
        type: boolean
      kubefirst_team:
        type: string
      last_condition:
        type: string
      private_key:
        type: string
      public_key:
        type: string
      public_keys:
        type: string
      state_store_create_check:
        type: boolean
      state_store_credentials:
        $ref: '#/definitions/types.StateStoreCredentials'
      state_store_creds_check:
        type: boolean
      state_store_details:
        $ref: '#/definitions/types.StateStoreDetails'
      status:
        type: string
      useTelemetry:
        description: Telemetry
        type: boolean
      users_terraform_apply_check:
        type: boolean
      vault_initialized_check:
        type: boolean
      vault_terraform_apply_check:
        type: boolean
      vultr_auth:
        $ref: '#/definitions/types.VultrAuth'
    type: object
  types.ClusterDefinition:
    properties:
      admin_email:
        type: string
      aws_auth:
        $ref: '#/definitions/types.AWSAuth'
      civo_auth:
        $ref: '#/definitions/types.CivoAuth'
      cloud_provider:
        enum:
        - aws
        - civo
        - digitalocean
        - vultr
        type: string
      cloud_region:
        type: string
      cluster_name:
        type: string
      do_auth:
        $ref: '#/definitions/types.DigitaloceanAuth'
      domain_name:
        type: string
      git_owner:
        type: string
      git_provider:
        enum:
        - github
        - gitlab
        type: string
      git_token:
        type: string
      type:
        enum:
        - mgmt
        - workload
        type: string
      vultr_auth:
        $ref: '#/definitions/types.VultrAuth'
    required:
    - admin_email
    - cloud_provider
    - cloud_region
    - domain_name
    - git_owner
    - git_provider
    - git_token
    - type
    type: object
  types.DigitaloceanAuth:
    properties:
      spaces_key:
        type: string
      spaces_secret:
        type: string
      token:
        type: string
    type: object
  types.ImportClusterRequest:
    properties:
      cloud_provider:
        type: string
      cloud_region:
        type: string
      cluster_name:
        type: string
      state_store_credentials:
        $ref: '#/definitions/types.StateStoreCredentials'
      state_store_details:
        $ref: '#/definitions/types.StateStoreDetails'
    type: object
  types.JSONFailureResponse:
    properties:
      error:
        example: err
        type: string
    type: object
  types.JSONHealthResponse:
    properties:
      status:
        example: healthy
        type: string
    type: object
  types.JSONSuccessResponse:
    properties:
      message:
        example: success
        type: string
    type: object
  types.StateStoreCredentials:
    properties:
      access_key_id:
        type: string
      id:
        type: string
      name:
        type: string
      secret_access_key:
        type: string
    type: object
  types.StateStoreDetails:
    properties:
      aws_artifacts_bucket:
        type: string
      aws_state_store_bucket:
        type: string
      hostname:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.VultrAuth:
    properties:
      token:
        type: string
    type: object
host: localhost:port
info:
  contact:
    email: help@kubefirst.io
    name: Kubefirst
  description: Kubefirst API
  title: Kubefirst API
  version: "1.0"
paths:
  /aws/domain/validate/:domain:
    get:
      consumes:
      - application/json
      description: Returns status of whether or not an AWS hosted zone is validated
        for use with Kubefirst
      parameters:
      - description: Domain name, no trailing dot
        in: path
        name: domain
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AWSDomainValidateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns status of whether or not an AWS hosted zone is validated for
        use with Kubefirst
      tags:
      - aws
  /aws/profiles:
    get:
      consumes:
      - application/json
      description: Returns a list of configured AWS profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AWSProfilesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns a list of configured AWS profiles
      tags:
      - aws
  /civo/domain/validate/:domain:
    get:
      consumes:
      - application/json
      description: Returns status of whether or not a Civo hosted zone is validated
        for use with Kubefirst
      parameters:
      - description: Domain name, no trailing dot
        in: path
        name: domain
        required: true
        type: string
      - description: Domain validation request in JSON format
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/types.CivoDomainValidationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CivoDomainValidationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns status of whether or not a Civo hosted zone is validated for
        use with Kubefirst
      tags:
      - civo
  /cluster:
    get:
      consumes:
      - application/json
      description: Return all known configured Kubefirst clusters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Cluster'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Return all known configured Kubefirst clusters
      tags:
      - cluster
  /cluster/:cluster_name:
    delete:
      consumes:
      - application/json
      description: Delete a Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Delete a Kubefirst cluster
      tags:
      - cluster
    get:
      consumes:
      - application/json
      description: Return a configured Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Cluster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Return a configured Kubefirst cluster
      tags:
      - cluster
    post:
      consumes:
      - application/json
      description: Create a Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      - description: Cluster create request in JSON format
        in: body
        name: definition
        required: true
        schema:
          $ref: '#/definitions/types.ClusterDefinition'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Create a Kubefirst cluster
      tags:
      - cluster
  /cluster/:cluster_name/export:
    post:
      consumes:
      - application/json
      description: Export a Kubefirst cluster database entry
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Export a Kubefirst cluster database entry
      tags:
      - cluster
  /cluster/:cluster_name/reset_progress:
    post:
      consumes:
      - application/json
      description: Remove a cluster progress marker from a cluster entry
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Remove a cluster progress marker from a cluster entry
      tags:
      - cluster
  /cluster/import:
    post:
      consumes:
      - application/json
      description: Import a Kubefirst cluster database entry
      parameters:
      - description: Cluster import request in JSON format
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/types.ImportClusterRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Import a Kubefirst cluster database entry
      tags:
      - cluster
  /domain/:cloud_provider:
    get:
      consumes:
      - application/json
      description: Return a configured Kubefirst cluster
      parameters:
      - description: The cloud provider to return registered domains/zones from
        in: path
        name: cloud_provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Cluster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Return a configured Kubefirst cluster
      tags:
      - domain
  /health:
    get:
      description: Return health status if the application is running.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.JSONHealthResponse'
      summary: Return health status if the application is running.
      tags:
      - health
  /stream:
    get:
      description: Stream API server logs
      responses: {}
      summary: Stream API server logs
      tags:
      - logs
swagger: "2.0"
