basePath: /api/v1
definitions:
  types.AWSDomainValidateResponse:
    properties:
      validated:
        type: boolean
    type: object
  types.AWSProfilesResponse:
    properties:
      profiles:
        items:
          type: string
        type: array
    type: object
  types.CivoDomainValidationRequest:
    properties:
      cloud_region:
        type: string
    type: object
  types.CivoDomainValidationResponse:
    properties:
      validated:
        type: boolean
    type: object
  types.Cluster:
    properties:
      alertsEmail:
        type: string
      argoCDAuthToken:
        type: string
      argoCDCreateRegistryCheck:
        type: boolean
      argoCDDeleteRegistryCheck:
        type: boolean
      argoCDInitializeCheck:
        type: boolean
      argoCDInstallCheck:
        type: boolean
      argoCDPassword:
        type: string
      argoCDUsername:
        type: string
      atlantisWebhookSecret:
        type: string
      atlantisWebhookURL:
        type: string
      awsaccountId:
        description: kms
        type: string
      awskmskeyDetokenizedCheck:
        type: boolean
      awskmskeyId:
        type: string
      civoToken:
        type: string
      cloudProvider:
        type: string
      cloudRegion:
        type: string
      cloudTerraformApplyCheck:
        type: boolean
      cloudTerraformApplyFailedCheck:
        type: boolean
      clusterID:
        type: string
      clusterName:
        type: string
      clusterSecretsCreatedCheck:
        type: boolean
      clusterType:
        type: string
      domainLivenessCheck:
        type: boolean
      domainName:
        type: string
      gitCredentialsCheck:
        type: boolean
      gitHost:
        type: string
      gitInitCheck:
        description: Checks
        type: boolean
      gitOwner:
        type: string
      gitProvider:
        type: string
      gitTerraformApplyCheck:
        type: boolean
      gitToken:
        type: string
      gitUser:
        type: string
      gitlabOwnerGroupID:
        type: integer
      gitopsPushedCheck:
        type: boolean
      gitopsReadyCheck:
        type: boolean
      id:
        type: string
      installToolsCheck:
        type: boolean
      kbotSetupCheck:
        type: boolean
      kubefirstTeam:
        type: string
      postDetokenizeCheck:
        type: boolean
      privateKey:
        type: string
      publicKey:
        type: string
      publicKeys:
        type: string
      stateStoreCreateCheck:
        type: boolean
      stateStoreCredentials:
        $ref: '#/definitions/types.StateStoreCredentials'
      stateStoreCredsCheck:
        type: boolean
      stateStoreDetails:
        $ref: '#/definitions/types.StateStoreDetails'
      usersTerraformApplyCheck:
        type: boolean
      vaultInitializedCheck:
        type: boolean
      vaultTerraformApplyCheck:
        type: boolean
    type: object
  types.ClusterDefinition:
    properties:
      admin_email:
        type: string
      cloud_provider:
        enum:
        - aws
        - civo
        - digitalocean
        - k3d
        - vultr
        type: string
      cloud_region:
        type: string
      cluster_name:
        type: string
      domain_name:
        type: string
      git_owner:
        type: string
      git_provider:
        enum:
        - github
        - gitlab
        type: string
      git_token:
        type: string
      type:
        enum:
        - mgmt
        - workload
        type: string
    required:
    - admin_email
    - cloud_provider
    - cloud_region
    - domain_name
    - git_owner
    - git_provider
    - git_token
    - type
    type: object
  types.JSONFailureResponse:
    properties:
      error:
        example: err
        type: string
    type: object
  types.JSONHealthResponse:
    properties:
      status:
        example: healthy
        type: string
    type: object
  types.JSONSuccessResponse:
    properties:
      message:
        example: success
        type: string
    type: object
  types.StateStoreCredentials:
    properties:
      accessKeyID:
        type: string
      id:
        type: string
      name:
        type: string
      secretAccessKey:
        type: string
    type: object
  types.StateStoreDetails:
    properties:
      awsartifactsBucket:
        type: string
      awsstateStoreBucket:
        type: string
      hostname:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:port
info:
  contact:
    email: help@kubefirst.io
    name: Kubefirst
  description: Kubefirst API
  title: Kubefirst API
  version: "1.0"
paths:
  /aws/domain/validate/:domain:
    get:
      consumes:
      - application/json
      description: Returns status of whether or not an AWS hosted zone is validated
        for use with Kubefirst
      parameters:
      - description: Domain name, no trailing dot
        in: path
        name: domain
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AWSDomainValidateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns status of whether or not an AWS hosted zone is validated for
        use with Kubefirst
      tags:
      - aws
  /aws/profiles:
    get:
      consumes:
      - application/json
      description: Returns a list of configured AWS profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AWSProfilesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns a list of configured AWS profiles
      tags:
      - aws
  /civo/domain/validate/:domain:
    get:
      consumes:
      - application/json
      description: Returns status of whether or not a Civo hosted zone is validated
        for use with Kubefirst
      parameters:
      - description: Domain name, no trailing dot
        in: path
        name: domain
        required: true
        type: string
      - description: Domain validation request in JSON format
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/types.CivoDomainValidationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CivoDomainValidationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Returns status of whether or not a Civo hosted zone is validated for
        use with Kubefirst
      tags:
      - civo
  /cluster:
    get:
      consumes:
      - application/json
      description: Return all known configured Kubefirst clusters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Cluster'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Return all known configured Kubefirst clusters
      tags:
      - cluster
  /cluster/:cluster_name:
    delete:
      consumes:
      - application/json
      description: Delete a Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Delete a Kubefirst cluster
      tags:
      - cluster
    get:
      consumes:
      - application/json
      description: Return a configured Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Cluster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Return a configured Kubefirst cluster
      tags:
      - cluster
    post:
      consumes:
      - application/json
      description: Create a Kubefirst cluster
      parameters:
      - description: Cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      - description: Cluster create request in JSON format
        in: body
        name: definition
        required: true
        schema:
          $ref: '#/definitions/types.ClusterDefinition'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.JSONSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.JSONFailureResponse'
      summary: Create a Kubefirst cluster
      tags:
      - cluster
  /health:
    get:
      description: Return health status if the application is running.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.JSONHealthResponse'
      summary: Return health status if the application is running.
      tags:
      - health
  /stream:
    get:
      description: Stream API server logs
      responses: {}
      summary: Stream API server logs
      tags:
      - logs
swagger: "2.0"
